applications:

  aws-efs-csi-driver-operator:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '5'
    destination:
      namespace: cert-manager
    source:
      path: groups/geo-east/overlays/aws-efs-csi-driver-operator